# Generated by Django 3.2.14 on 2024-07-12 18:36

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='nouns',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='verbs',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
